name: mirrorchyan trigger

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to test'
        required: true
        default: 'v0.0.4'

jobs:
  run:
    runs-on: windows-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Trigger MirrorChyanUploading
        shell: bash
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release.yml -f tag=${{ inputs.tag }}
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note.yml -f tag=${{ inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
